spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL;
    username: sa
    password:
    initialization-mode: always
    schema: classpath:mysql/schema.sql
    data: classpath:mysql/data.sql
  h2:
    console:
      enabled: true

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:debug}